name: PR for master

on:
  pull_request:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Install pre-commit
        run: |
          sudo pip3 install pre-commit

      - name: Run precommit
        run: |
          pre-commit run --all-files
          git add -A
          git commit -m '(ci skip): Automated code quality fixes from pre-commit in github actions'
          git push origin master