name: PR for master

on:
  pull_request:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Log into registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Pull Docker Image
        run: |
          docker pull docker.pkg.github.com/aws-cloudformation/aws-cloudformation-resource-providers-transitgateway/precommit:try-github-actions
      - name: Run precommit
        run: |
          docker run -v $GITHUB_WORKSPACE/:/app -t precommit:try-github-actions pre-commit run --all-files
      - name: Recommit
        run: |
          git config --list
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -am "(ci skip): Automated code quality fixes from pre-commit in github actions"
          git push
