name: PR for master

on:
  pull_request:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Install pre-commit
        run: |
          docker build --build-arg GITHUB_USERNAME=${GITHUB_USERNAME} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} --build-arg APP_NAME=$GITHUB_REPOSITORY . -t precommit

      - name: Run precommit
        run: |
          docker run -v $GITHUB_WORKSPACE/:/app -t precommit pre-commit run --all-files
          git add -A
          git commit -m '(ci skip): Automated code quality fixes from pre-commit in github actions'
          git push origin master
